apiVersion: scheduling.hypershift.openshift.io/v1alpha1
kind: ClusterSizingConfiguration
metadata:
  name: cluster
spec:
  concurrency:
    limit: 5
    slidingWindow: 0s
  sizes:
  - criteria:
      from: 0
      to: 60
    effects:
      maximumMutatingRequestsInflight: 50
      maximumRequestsInflight: 150
      resourceRequests:
      - containerName: kube-apiserver
        deploymentName: kube-apiserver
        memory: 8Gi
      - containerName: openshift-controller-manager
        deploymentName: openshift-controller-manager
        memory: 1Gi
      - containerName: cluster-policy-controller
        deploymentName: cluster-policy-controller
        memory: 1Gi
      - containerName: kube-controller-manager
        deploymentName: kube-controller-manager
        memory: 1Gi
      - containerName: openshift-apiserver
        deploymentName: openshift-apiserver
        memory: 1Gi
    name: small
  - criteria:
      from: 61
      to: 120
    effects:
      kasGoMemLimit: 12GiB
      maximumMutatingRequestsInflight: 300
      maximumRequestsInflight: 900
      resourceRequests:
      - containerName: kube-apiserver
        deploymentName: kube-apiserver
        memory: 16Gi
    name: medium
  - criteria:
      from: 121
      to: 252
    effects:
      kasGoMemLimit: 24GiB
      maximumMutatingRequestsInflight: 400
      maximumRequestsInflight: 1200
      resourceRequests:
      - containerName: kube-apiserver
        deploymentName: kube-apiserver
        memory: 32Gi
    name: large
  - criteria:
      from: 253
      to: 360
    effects:
      kasGoMemLimit: 48GiB
      maximumMutatingRequestsInflight: 600
      maximumRequestsInflight: 2400
      resourceRequests:
      - containerName: kube-apiserver
        deploymentName: kube-apiserver
        memory: 64Gi
    name: xlarge        
  - criteria:
      from: 361
    effects:      
      kasGoMemLimit: 72GiB
      resourceRequests:
      - containerName: kube-apiserver
        deploymentName: kube-apiserver
        memory: 96Gi
    name: xxlarge
  transitionDelay:
    decrease: 0s
    increase: 0s
