kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    scrape_configs:
    - job_name: node_runtime
      sample_limit: 12000
      follow_redirects: false
      scheme: http
      scrape_interval: 30s
      metrics_path: /v1/metrics
      static_configs:
      - targets:
        - '$NODE_IP:10257'
      relabel_configs:
      - source_labels: [__address__]
        replacement: '$NODE_NAME'
        target_label: instance
      - source_labels: [__metrics_path__]
        regex: (.*)
        target_label: metrics_path
metadata:
  name: ama-metrics-prometheus-config-node
  namespace: kube-system
